
          // Generated by CoffeeScript 2.0.0-beta4
var cube, square;
square = function (x) {
  return x * x;
};
cube = function (x) {
  return square(x) * x;
};
alert(cube(5));

          /*
          //@ sourceMappingURL=example.map
          */
        
