// Generated by CoffeeScript 2.0.0-beta4
void function () {
  var cube, square;
  square = function (x) {
    return x * x;
  };
  cube = function (x) {
    return square(x) * x;
  };
  alert(cube(5));
}.call(this);

/*
//@ sourceMappingURL=example/simple-coffee-redux/example.map
*/
